PREFIX : <http://voc.zazuko.com/zack#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  text: <http://jena.apache.org/text#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  :query :result ?sub .
  ?sub a :resultItem .
  ?sub ?pred ?obj .
  ?sub :score ?score .
} WHERE {
  {
    SELECT  ?sub ?score WHERE {
      GRAPH <http://data.alod.ch/graph/inference-supertitle> {
        (?sub ?score ?literal) text:query (skos:hiddenLabel "${searchString}") .
      }${filters}
    }
    OFFSET ${offset}
    LIMIT ${limit}
  }
  GRAPH ?g {
    ?sub ?pred ?obj .
  }
}
