import clownface from 'clownface'
import $rdf from 'rdf-ext'
import { schema } from '@tpluscode/rdf-ns-builders/strict'

export default clownface({ dataset: $rdf.dataset() })
  .blankNode()
  .addOut(schema.name, 'zack-lists.default-list')
  .addOut(schema.value, 'Starred')
  .blankNode()
  .addOut(schema.name, 'zack-lists.select-list')
  .addOut(schema.value, 'Select list')
  .blankNode()
  .addOut(schema.name, 'zack-fav-menu.notes')
  .addOut(schema.value, 'Notes')
  .blankNode()
  .addOut(schema.name, 'zack-fav-menu.edit-notes')
  .addOut(schema.value, 'Edit notes')
  .blankNode()
  .addOut(schema.name, 'zack-fav-menu.lists-header')
  .addOut(schema.value, 'Lists')
  .blankNode()
  .addOut(schema.name, 'zack-fav-menu.select-not-starred')
  .addOut(schema.value, 'Not starred')
  .blankNode()
  .addOut(schema.name, 'zack-lists-dialog.add-list')
  .addOut(schema.value, 'Add list')
  .blankNode()
  .addOut(schema.name, 'zack-lists-dialog.header')
  .addOut(schema.value, 'Lists')
  .blankNode()
  .addOut(schema.name, 'zack-lists-dialog.new-list-placeholder')
  .addOut(schema.value, 'New list')
  .blankNode()
  .addOut(schema.name, 'zack-notes-dialog.header')
  .addOut(schema.value, 'Notes')
  .blankNode()
  .addOut(schema.name, 'zack-starred-dialog.add-note')
  .addOut(schema.value, 'Add note')
  .blankNode()
  .addOut(schema.name, 'zack-starred-dialog.item-starred')
  .addOut(schema.value, 'Starred item')
  .blankNode()
  .addOut(schema.name, 'zack-filter-summary.list-prefix')
  .addOut(schema.value, 'list')
